url: https://angelsk.games
title: Angel on Xbox
description: I play games
theme: jekyll-theme-cayman
google_analytics: UA-120806255-1
twitter:
  username: angelsk
  card: summary
logo: /assets/images/logo-purple.png
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo-large-banner.png
image: /assets/images/logo-large-banner.png
lang: en_GB
social:
  name: Jo Carter
  links:
    - https://twitter.com/angelsk
    - https://mixer.com/angelsk
    - https://www.youtube.com/c/JoCarterAngelSK
    - https://account.xbox.com/en-GB/Profile?gamerTag=angelsk
    - https://www.trueachievements.com/gamer/angelsk
    - http://www.thatpodcastthing.co.uk/
